### ISSUE TITLE
[Bug] When inventory is full and taking a picture, the image will simply disappear and cost a paper

### ISSUE THREAD

**Issue by Anonyku05** [chrrs/camerapture#10]
### What's the issue?

As said in the tile, this bug is not making the game unplayable but still a minor issue that is worth reporting

### Mod and Minecraft version

1.2.1, Fabric 1.20.4

**Comment by chrrs** [comment]
Are you sure it doesn't get dropped on the ground? I just tested it, and if your inventory is full, it should just drop the picture item in front of you.

**Comment by chrrs** [comment]
Huh, that's weird. I've been trying some combinations of things, but I can't seem to recreate it. I think it might be a compatiblity issue with another mod.

I also see the error message in chat, which indicates an issue on the server. I'm not sure if you've got access to the server logs (or client logs in case of a single player world), but if you do, and know how to, are you able to look if there's any error in there (just Ctrl+F search for "camerapture"), and send it here if there is? Thank you!

**Comment by Anonyku05** [comment]
There you go, this log is after launching the game, a sp world, making my inventory full and trying to take a picture with the error message:
https://pastebin.com/qnyBEf5J

**Comment by chrrs** [comment]
Ah, thank you so much, I see the problem now. It's a compatibility issue with the Concurrent Chunk Management Engine mod that happens when trying to drop the picture item in the world. It shouldn't be too much work to fix that! I'll get it done soon, thank you!!
