### ISSUE TITLE
could not fetch image

### ISSUE THREAD

**Issue by Orangutanlover97** [chrrs/camerapture#12]
### What's the issue?

Hey-o i love this mod but whenever i go in and out of my world the images disappear and get replaced with text that says could not fetch image. the images are still on my pc and have not been moved or anything so idk what causes this

### Screenshots

![image_2024-06-15_000058561](https://github.com/chrrs/camerapture/assets/172856645/95e0868c-43ba-4e5a-8b6e-71f22af8bf7f)
![image_2024-06-15_000158895](https://github.com/chrrs/camerapture/assets/172856645/51810de5-87b4-4023-bbf8-51104ae08653)

### Mod and Minecraft version

Camerapture-1.3.0+mc1.20.1

**Comment by Orangutanlover97** [comment]
also sometimes when using the camera i dont receive the image
![image_2024-06-15_001644453](https://github.com/chrrs/camerapture/assets/172856645/9c17719d-a0c2-432a-8ec0-f8c569f5ec92)

**Comment by chrrs** [comment]
This might be an issue I'm aware of! Are you using the Essential mod?

**Comment by Orangutanlover97** [comment]
yeah i am!

**Comment by chrrs** [comment]
In that case, if it's what I think it is, I released version 1.3.1 that should fix this!

**Comment by Orangutanlover97** [comment]
thank you so much this worked!
