### ISSUE TITLE
[Suggestion]: Allowing pictures to be put on a map

### ISSUE THREAD

**Issue by Anonyku05** [chrrs/camerapture#13]
### What do you want added or changed?

As said in the title, allowing the pictures to be put on maps, like a polaroïd camera

**Comment by chrrs** [comment]
Hmmm wait what exactly do you mean? There's already pictures you can look at and hang on the wall, so what would maps add that isn't there right now?

**Comment by Anonyku05** [comment]
I meant like this, it already exist on another mod:
![image](https://github.com/chrrs/camerapture/assets/48128391/2949b0c3-bed5-4046-81d8-5a4b7a859044)

But if it's too complicated or you just don't have the motrivation for it it's okay. Was only suggesting cuz it would be cool to see the pic directly on the hand

**Comment by chrrs** [comment]
It would be really cool to hold the pictures in your hand, but right now I can't really think of a place where it would fit into the mod. If you do want it to be specifically on a map, you could download Image2Map and upload the image manually. I'll think about it some more!

**Comment by chrrs** [comment]
I've thought about it, I don't think I'll add anything like this for now, sorry!

**Comment by Anonyku05** [comment]
I haven't noticed that in the mod there was a thing called the Album, so my suggestion was useless in the end anyway !
