### ISSUE TITLE
[Mod compatibility] First person model

### ISSUE THREAD

**Issue by Anonyku05** [chrrs/camerapture#18]
### What's the issue?

Basically just wanted to know if it is possible to make the mod "compatible" with the [first person model mod](https://modrinth.com/mod/first-person-model)

### Screenshots

![4ab63833-f3e5-4c36-8848-c92133d92baa](https://github.com/user-attachments/assets/08efede3-00c4-4f3a-bbd1-aec9f7d232b7)

### Mod and Minecraft version

Camerapture 1.6.0 and Minecraft 1.20.4

**Comment by chrrs** [comment]
A solution would be to disable the mod when taking pictures (I think by default pressing F6 will toggle the first person view model), but ideally there should be some kind of compatibility, yeah. I'll work on that!
