### ISSUE TITLE
Fetching picture permentaly

### ISSUE THREAD

**Issue by Jwoosey** [chrrs/camerapture#19]
### What's the issue?

Every image in the world is just permanently stuck on fetching picture loading thing forever
its every image

Only fix is to go down to the 1.4.1 version of 1.20.1 but with that version i cant resize images
it was working fine before and randomly just broke

### Screenshots

![2024-07-18_02 23 52](https://github.com/user-attachments/assets/f8a324c6-8366-4d21-a649-918229ab5dbc)

### Mod and Minecraft version

Camerapture for 1.20.1

**Comment by chrrs** [comment]
Hello! Could you look in your game's log files to see if there's any error, or alternatively upload the log file to https://mclo.gs/? And, just to make sure, this is happening on the latest version (1.6.0), right?
