### ISSUE TITLE
[1.21 - Crash] Conflict with PolyLib

### ISSUE THREAD

**Issue by KhanhPham05** [chrrs/camerapture#21]
### What's the issue?

Mixin conflict with the mod PolyLib [0.3-159](https://www.curseforge.com/minecraft/mc-mods/polylib/files/5590873)

`
@Redirect conflict. Skipping polylib-fabric.mixins.json:AbstractContainerScreenMixin from mod polylib->@Redirect::redirectHighlight(Lnet/minecraft/class_332;III)V with priority 1000, already redirected by camerapture-client.mixins.json:HandledScreenMixin from mod camerapture->@Redirect::drawSlotHighlight(Lnet/minecraft/class_332;III)V with priority 1000
`

### Mod and Minecraft version

Camerapture 1.6.1 - MC 1.21

**Comment by chrrs** [comment]
Thank you for the report! That should be a pretty easy fix!
