### ISSUE TITLE
Do pictures cause lag

### ISSUE THREAD

**Issue by DoozyYay** [chrrs/camerapture#23]
### What your question?

I wanted to know if pictures can cause lag when placed. I'm asking this because I don't know if it's similar to item frames or paintings where if u place so many it starts to lag, and I'm worried and wanna know the answer before I decide on placing tons of pictures in a build.

**Comment by chrrs** [comment]
It's similar to paintings, and a lot more efficient than item frames. The lag should not be noticeable as long as you're not intentionally trying to test the limits.
