### ISSUE TITLE
Naming Pictures

### ISSUE THREAD

**Issue by DoozyYay** [chrrs/camerapture#24]
### What do you want added or changed?

I think a great feature would be the option to set a name for any picture you create. You can already do this with an anvil but that can be tedious and waste a lot of XP. Either this, or another feature which could be great is to allow the player to see what the image actually is by hovering over the item in their inventory. I also have over 40 pictures in my SMP just with the name "Picture" so any of these features would be very helpful.

**Comment by chrrs** [comment]
I like the current way that it works by naming it in an anvil, but I do agree it should be easier to sort the pictures in your inventory. Instead, maybe I could add it so that you can see the picture in the tooltip when hovering.
