### ISSUE TITLE
Picture and options apear when others use them

### ISSUE THREAD

**Issue by Magnilla06** [chrrs/camerapture#3]
I'm playing on a world with a friend using essential, and everytime they open a picture or change a picture the option appears on my screen too (I'm the host). I'm not sure why this happens or how to fix it :/

**Comment by chrrs** [comment]
Ah oops, sorry about that! I'm pretty sure I know exactly whats causing that, an oversight that would only happen on locally hosted worlds (in this case with Essential). I'll release a new version with the fix in the next hour or so. Thank you for reporting!

**Comment by chrrs** [comment]
Version 1.1.4 with the fix is now released!
