### ISSUE TITLE
Incompatible with Forge + Sinytra Connector

### ISSUE THREAD

**Issue by LehaKat** [chrrs/camerapture#32]
### What's the issue?

Well this)
[crash-2024-10-21_18.18.21-fml.txt](https://github.com/user-attachments/files/17463257/crash-2024-10-21_18.18.21-fml.txt)

### Screenshots

![Снимок экрана 2024-10-21 181955](https://github.com/user-attachments/assets/54480a8d-195f-4953-9eb3-0b1bb807c4ed)

### Mod and Minecraft version

Camerapture-1.6.2+mc1.20.1

**Comment by chrrs** [comment]
It looks like you're running on Forge with Sinytra connector, which is not something I've ever tested or supported, so I'm not sure yet if I can make that work properly. I'll take a look though!

**Comment by LehaKat** [comment]
> Похоже, вы работаете на Forge с коннектором Sinytra, который я никогда не тестировал и не поддерживал, поэтому я пока не уверен, смогу ли заставить его работать должным образом. Я посмотрю!

Yes, you are right about the Sinytra connector, It would be great if it worked) Thank you ❤

**Comment by chrrs** [comment]
I've released an alpha version thats native for Forge, so this is not an issue anymore!

**Comment by LehaKat** [comment]
> Я выпустил альфа-версию, которая предназначена для Forge, так что это больше не проблема!

OMG THANK YOU ❤❤❤
