### ISSUE TITLE
Mod doesn't work in server instances.

### ISSUE THREAD

**Issue by JacobTDC** [chrrs/camerapture#34]
### What's the issue?

Server instances with Camerapture installed crash on startup.

I'm using `fabric-server-mc.1.20.1-loader.0.16.9-launcher.1.0.1.jar` with no extra arguments (other than `-Xmx`), and openjdk-17-jre.

[latest.log](https://github.com/user-attachments/files/18139019/latest.log)
(no crash report generated)

### What loader are you using?

Fabric

### What is your Minecraft version?

1.20.1

### What is Camerapture's version?

Camerapture 1.7.1

**Comment by chrrs** [comment]
Oops, small oversight by me! Should be fixed in the next version!
