### ISSUE TITLE
Camera HUD is linked to hotbar [Raised incompatibility?]

### ISSUE THREAD

**Issue by JohnGoten** [chrrs/camerapture#35]
### What's the issue?

Using Raised (https://modrinth.com/mod/raised v4.0.1) I discovered that having my hotbar moved using the mod it would create a duplicated equally moved image of the camera HUD on-screen.

![2024-12-15_15 41 13](https://github.com/user-attachments/assets/6d24fbb7-3842-41e1-8ca3-038d1750a1c0)
using an 8 pixel offset on the y-axis in this example; standalone test instance: https://mclo.gs/dy402nH

Although having dealt with an oddly similar case just before, I am still a mere end user lacking the knowledge and understanding of what truly goes on behind the scenes. For all I know is that it needs not be attached to the hotbar in order to retain regular Raised functionality. Nevertheless I am pretty sure this is likely to be resolved on your end, hence why I am not yet bringing this up to yukisuika as previously

### What loader are you using?

NeoForge

### What is your Minecraft version?

1.21.1

### What is Camerapture's version?

1.7.1

**Comment by chrrs** [comment]
Yes, you're right, this is an issue on my side, the solution should be pretty simple! Thank you for the report!
