### ISSUE TITLE
Album/Gallery or a Scrapbook Feature.

### ISSUE THREAD

**Issue by whatamaniac** [chrrs/camerapture#6]
### What do you want added or changed?

An Album like a Book type where you'll see all the images captured or uploaded by the user one by one or specifically chosen pictures and an inventory to store images (when opening the album shows every stored image one by one) we made a bakery menu in our last smp by renaming the Album to Menu and added photoshoped pictures of Ingame bakery food items. Works great with uploaded edited images. 
or a Gallery button on to the camera itself which shows up under the "Upload Picture" ui when crouch right click with camera. When clicking on the Gallery button opens up a "+" ui or sort of empty screen at first. when clicking on "+" ui on the empty screen > opens up a selection screen where there's a list and small thumbnails of every image captured or uploaded by user and filename (and if possible an option to rename and delete specific images which were taken accidentally) > after selecting some specific pictures it adds an Virtual Album next to the "+ icon" on the previous empty screen with a thumbnail as the first picture of the album and a feature to rename every created album like "Trip to the Nether" or "Journey to the Deep Dark Dimension" etc. 

A Scrapbook where you can store specific captured or uploaded images (shift right click opens up a large chest sort of inventory where images can be stored) and after normal right click opens the first page which is a Cover Page where you can Name or Title the album. when opening the book opens up a screen of an Open book ui with 2 pages where every page consists of 4-6 Images (total 8-12 polaroid or map shaped thumbnail) when clicking on every thumbnail opens up a Larger picture of every image (and showing the name of the image under the picture only if renamed the item thru anvil).

**Comment by chrrs** [comment]
Ooooo yes! I do want some kind of way to combine pictures, or to like collect them in a book. I'll need to think of the best way to do that though. I think I want some kind of album at the very least, which you can just scroll through all the pictures full-screen. I do also really like your scrapbook idea, but I'm not sure where that would fit in right now. I'll think about it!

**Comment by whatamaniac** [comment]
> Ooooo yes! I do want some kind of way to combine pictures, or to like collect them in a book. I'll need to think of the best way to do that though. I think I want some kind of album at the very least, which you can just scroll through all the pictures full-screen. I do also really like your scrapbook idea, but I'm not sure where that would fit in right now. I'll think about it!

Another thing that I wanna appreciate that your mod has which I wanted to have years ago when I was first introduced to the forge camera mod... I wanted to add png images with transparent background and it wasn't possible for some reason the transparent background would turn into black bg. But when I tried that with your mod recently I was very happy that it worked (especially the glowing option.. it's really great). Thank you for this mod.. really wanted this on Fabric. I'll share some of the really cool ideas with pictures in some days that we're using in our SMP with the help of the transparent background thingy. Also I know it's a lot to think and to implement the album or scrapbook feature.... But everything has a start... As you said a way to store images a view them would be a great start. Looking forward to it. =]

**Comment by chrrs** [comment]
Took a little bit, but albums are now in mod version 1.3.0!

**Comment by whatamaniac** [comment]
Hey man honestly speaking.. I love the albums. Exactly how i imagined it to be. Great Job done in such a short period of time. Loved it.

**Comment by chrrs** [comment]
So happy to hear that!! It's genuinely really cool to see others having fun with the silly mod that I made :)
